version: '3.8'
services:
  db:
    image: postgres:15
    container_name: Supply_Ease
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: SupplyEase
      POSTGRES_DB: SupplyEaseDB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: